$(document).ready(function(){
    $("button").click(function(){
        $("p").hide();
    });
    $("button").click(function(){
        $("#p_01").hide();
    });
    $("button").click(function(){
        $("#cp_01").hide();
    });
});